language: php

php:
  - 5.5
  - 5.6
  - hhvm-nightly

env:
  - DB=mysql

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2
  - sudo apt-get install wget
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  - sudo ln -s ../dbmng2 /var/www/
  - sudo ls /var/www/dbmng2/
  - wget http://localhost/dbmng2/LICENSE
  - composer --prefer-source --dev install
  - cp phpunit.xml.dist phpunit.xml
  - cp settings.default.php settings.php
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS dbmng2;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql dbmng2 < sql/dbmng2.sql -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql dbmng2 < sql/test.sql -uroot; fi
