language: php

php:
  - 5.5
  - 5.6
  - hhvm-nightly

env:
  - DB=mysql

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - sudo chmod +x install_travis.sh
  - sudo ./install_travis.sh
  - composer --prefer-source --dev install
  - cp phpunit.xml.dist phpunit.xml
  - cp settings.default.php settings.php
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS dbmng2;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql dbmng2 < sql/dbmng2.sql -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql dbmng2 < sql/test.sql -uroot; fi
